<?php

namespace Framework2\Example;

use Framework2\Console\Routes;
use Framework2\Templating\PageBuilder;

class Console
{
    /**
     * @var Routes
     */
    private $routes;

    /**
     * @var PageBuilder
     */
    private $pageBuilder;

    public function __construct(Routes $routes, PageBuilder $pageBuilder)
    {
        $this->routes = $routes;
        $this->pageBuilder = $pageBuilder;
    }

    public function showExample()
    {
        ob_start();
        $this->routes->listRoutes();
        $output = ob_get_clean();

        $page = $this->pageBuilder->create()
                ->setTitle('Console usage')
                ->setBody("<h1>Console usage</h1>
                        <p>A console-based entry point to the framework is available. The below output can be generated by running:</p>
                        <p style='font-size: x-large; font-weight: bold; font-family: monospace;'>$ ./console " . \ConsoleRoutes::LIST_ROUTES . "</p>
                        <pre>{$output}</pre>
                        <p>Controller action was <em>" . __METHOD__ . "();</em></p>");

        echo $this->pageBuilder->render($page);
    }
}